config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods
    get '/add_food/', to: 'recipe_foods#add_food'
    get '/shopping_list', to: 'recipes#shopping_list'
  end

  get '/public_recipes', to: 'recipes#public_recipes'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Root for the Shoping list
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 250 }
  validates :preparation_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { minimum: 2, maximum: 9999 }

  def total_cost
    total = 0
    recipe_foods.includes(:food).each do |recipe_food|
      total += recipe_food.quantity * recipe_food.food.price
    end
    total.round(2)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    @recipes = @current_user.recipes
  end

  # GET /public_recipes

  def public_recipes
    @public_recipes = Recipe.all.where(public: true).order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = @recipe.recipe_foods.includes(:food, :recipe)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @user = current_user
    @recipe = @current_user.recipes.create(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Shopping List
  def shopping_list
    @total_value = 0
    recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = recipe.recipe_foods.includes(:food).select do |recipe_food|
      food = recipe_food.food
      user_food = current_user.foods.find_by(name: food.name, measurement_unit: food.measurement_unit)
      @total_value += recipe_food.process_cost(user_food)
      recipe_food.process_quantity(user_food).positive?
    end
    @total_value = @total_value.round(2)
    @items_to_buy = @recipe_foods.count
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe-show.html.erb
<div>


<div class="recipe-card">

<div>
  <p>
    <strong>Preparation time (min):</strong>
    <%= @recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time (min):</strong>
    <%= @recipe.cooking_time %>
  </p>
</div>

<p>
    <strong>Public:</strong>
    <label class="switch">
      <input type="checkbox" role="switch" <%= 'checked' if @recipe.public %> disabled>
      <span class="slider round"></span>
    </label>
  </p>

</div>

  <p>
    <strong>Description:</strong>
    <%= @recipe.description %>
  </p>

  
  <div class="d-flex justify-content-between">
    <%= link_to 'Generate Shopping List', recipe_shopping_list_path(@recipe), class: 'btn btn-secondary' %>

    <% if can? :manage, @recipe %>
      <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn btn-success' %>
    <% end %>
  </div>
  <%= render 'shared/food_table' do %>
    <%= render @recipe_foods %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="page-title">
  <h1>Welcome to <%= @current_user.name%>'s Recipes</h1>
</div>

<% if @recipes.empty? %>
        <h3>Currently there aren't recipes in the database for this user</h3>
      <% else %>

<div class="recipe-list">

  <% @recipes.each do |recipe| %>
    <div class="recipe-card">

      <div class="name-and-remove">

  <h3 class="recipe-name">
    
    <%= link_to recipe.name, recipe, class:"link" %>
  </h3>

<p>
<%= button_to "REMOVE", recipe_path(recipe.id), method: :delete, class: 'delete-btn'%>
    </p>

    <%
=begin%>
 <% if can? :manage, recipe %>
      <%= button_to "Delete this recipe", @recipe, method: :delete, class: 'delete-btn'%>
    <% end %> 
<%
=end%>

</div>


<p class="recipe-description">
   
    <%= link_to recipe.description, recipe, class:"link" %>
  </p>
  


</div>
    

  <% end %>

</div>
<% end %>
  <%= link_to "Create a new recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<div class="page-title">
  <h1>Public Recipes</h1>
</div>

<% if @public_recipes.empty? %>
        <h3>Currently there aren't public recipes in the database</h3>
      <% else %>

<div class="recipe-list">

  <% @public_recipes.each do |recipe| %>
   <div class="recipe-card">
  
    <div class="card-content1">
  <p>
     <h3><%= link_to recipe.name, recipe, class:"link" %></h3>
  </p>

<h4><%= "By #{recipe.user.name}" %></h4>
  
  </div>

<div class="card-content2">

  <p><strong>Total food items: </strong><%= recipe.recipe_foods.count %></p>
  <p><strong>Total price ($): </strong><%= number_to_currency(recipe.total_cost) %></p>
    
  </div>
  
</div>

  <% end %>

<% end %>

<%= link_to "Back to recipes", recipes_path %>

app/views/recipes/shopping_list.html.erb
12 lines (10 sloc)  324 Bytes

<h1>Shopping List</h1>

<div>
  <div>Amount of items to buy: <%= @items_to_buy %></div>
  <div>Total value of food needed: <%= @total_value %></div>
</div>

<%= render 'shared/shopping_table' do %>
  <% @recipe_foods.each do |recipe_food| %>
    <%= render 'recipe_foods/shopping_item', recipe_food: %>
  <% end %>
<% end %>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="page-title">
  <h1>
    <%= @recipe.name %>
  </h1>
</div>

<div class="recipe-details">

<%= render 'recipe-show' %>

<hr>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  </div>
</div>