config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods
    get '/add_food/', to: 'recipe_foods#add_food'
    get '/shopping_list', to: 'recipes#shopping_list'
  end

  get '/public_recipes', to: 'recipes#public_recipes'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Root for the Shoping list
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/models/food.rb
class Food < ApplicationRecord
  # Data Relationships
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  # Data Validation
  validates :name, presence: true, length: { minimum: 2, maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @user = current_user
    @foods = @user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # Shopping List
  def general_shopping_list
    @total_value = 0
    @items_to_buy = 0
    @foods = current_user.foods
    @foods.each do |food|
      recipe_food = RecipeFood.find_by(food:)
      next if recipe_food.nil?

      @items_to_buy += 1 if recipe_food.process_quantity(food).positive?
      @total_value += recipe_food.process_cost(food)
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
    @user = current_user
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<tr id="<%= dom_id food %>" class="single-food">
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td><%= food.quantity %></td>
  <td><%= link_to "Edit this food", edit_food_path(food) %></td>
  <td><%= button_to "Destroy this food", food_path(food.id), method: :delete %></td>
</tr>

<td><%# button_to "Destroy this food", @food, method: :delete %></td>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/_shopping_item.erb
<tr>
  <td><%= food.name %></td>
  <td><%= recipe_food.process_quantity(food) %> <%= food.measurement_unit %></td>
  <td><%= number_to_currency(recipe_food.process_cost(food)) %></td>
</tr>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/general_shopping_list.html.erb
<h1>Shopping List</h1>

<div>
  <div>Amount of items to buy: <%= @items_to_buy %></div>
  <div>Total value of food needed: <%= @total_value %></div>
</div>

<%= render 'shared/shopping_table' do %>
  <% @foods.each do |food| %>
    <% recipe_food = RecipeFood.find_by(food:) %>
    <% unless recipe_food.nil? %>
      <%= render 'shopping_item', food:, recipe_food: %>
    <% end %>
  <% end %>
<% end %>

app/views/foods/index.html.erb
<main class="foods-container">
  <p style="color: green"><%= notice %></p>

  <h1>Welcome to the food list of <%= @user.name %></h1>

  <section id="foods">
    <% if @foods.empty? %>
      <h2>There are no foods added to this user</h2>
    <% else %>
      <table class="food-items-container">
        <tr class="food-items-titles">
          <th>Food</th>
          <th>Measurement unit</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Edit Food</th>
          <th>Delete this food</th>
        </tr>

        <% @foods.each do |food| %>
          <%= render food %>
        <% end %>
      </table>
    <% end %>
  </section>

  <%= link_to "New food", new_food_path %>
</main>

app/views/foods/new.html.erb
<h1>Let's add your food here</h1>

<%= render "form", food: @food %>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="food-items-container">
  <tr class="food-items-titles">
    <th>Food</th>
    <th>Measurement unit</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Edit Food</th>
    <th>Delete this food</th>
  </tr>
<%= render @food %>
</table>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>