config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods
    get '/add_food/', to: 'recipe_foods#add_food'
    get '/shopping_list', to: 'recipes#shopping_list'
  end

  get '/public_recipes', to: 'recipes#public_recipes'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Root for the Shoping list
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  attr_accessor :quantity_needed, :cost_required

  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def process_quantity(user_food)
    return @quantity_needed = quantity unless user_food

    diff = user_food.quantity - quantity
    @quantity_needed = diff.negative? ? -diff : 0
  end

  def process_cost(user_food)
    @cost_required = (process_quantity(user_food) * food.price).round(2)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]
  before_action :set_recipe
  before_action :set_user

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.find_by(@recipe).includes(:food)
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(@recipe_food.recipe), notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_foods_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_food
    redirect_to new_food_path and return
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id]).includes(:food)
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_user
    @user = current_user
    @foods = @user.foods
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food, url: recipe_recipe_foods_path(recipe), method: :post) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :food_id, style: "display: block", class: "form-label" %>
    <%= form.select :food_id, @foods.map {|food| ["#{food.name} in #{food.measurement_unit}", food.id]}, {}, { class: 'form-select form-select-lg' } %>
    If food not present you may <%= link_to 'Add New Food', action: :add_food %>
  </div>
  <div class="mb-3">
    <%= form.label :quantity, style: "display: block", class: "form-label" %>
    <%= form.number_field :quantity,  class: "form-control m-2 w-50"%>
  </div>
  <div>
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.food.measurement_unit %></td>
  <td>$<%= recipe_food.food.price %></td>
  <td><%= recipe_food.quantity %></td>
  <td class="d-flex justify-content-evenly">
    <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_food.recipe, recipe_food), class: "btn btn-primary" %>
    <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :delete, class: "btn btn-danger" %></td>
</tr>

app/views/recipe_foods/_shopping_item.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity_needed %> <%= recipe_food.food.measurement_unit %></td>
  <td>$<%= recipe_food.cost_required %></td>
</tr>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", recipe_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_path(@recipe_food.recipe) %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food, recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_recipe_foods_path(@recipe) %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_recipe_food_path(@recipe_food.recipe, @recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_recipe_foods_path(@recipe_food.recipe) %>
  <%= button_to "Destroy this recipe food", url: recipe_recipe_food_url(@recipe_food.recipe, @recipe_food), method: :delete %>
</div>