config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  
  resources :recipes do
    resources :recipe_foods
    get '/add_food/', to: 'recipe_foods#add_food'
    get '/shopping_list', to: 'recipes#shopping_list'
  end

  get '/public_recipes', to: 'recipes#public_recipes'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Root for the Shoping list
  get '/general_shopping_list', to: 'foods#general_shopping_list'

  # Defines the root path route ("/")
  root "recipes#public_recipes"
end

app/views/layouts/_navbar.html.erb
<div class="navlogo">
  <%= image_tag ("logo_recipe3.png"), class: 'logo' %>

<% if user_signed_in? %>
  <nav>
  
    <ul class="navbar-items">
      <li><%= link_to "Foods", foods_path, class: "navbar-list-item" %></li>
      <li><%= link_to "Recipes", recipes_path, class: "navbar-list-item" %></li>
      <li><%= link_to "Public Recipes", public_recipes_path, class: "navbar-list-item" %></li>
      <li><%= link_to "Shopping List", general_shopping_list_path, class: "navbar-list-item" %></li>
    </ul>

    <ul class="navbar-items">
      <li><%= link_to "Sign in", new_user_session_path, class: "navbar-list-item" %></li>
      <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"navbar-list-item navbar-button-link" %></li>
      <li><%= link_to "Account", edit_user_registration_path, class: "navbar-list-item" %></li>
      <li><p class="navbar-list-item">Current user: <%= current_user.name %></p></li>
    </ul>
  </nav>
<% else %>
  <nav>
    <ul class="navbar-items">
      <li><%= link_to "Sign in", new_user_session_path, class: "navbar-list-item" %></li>
      <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"navbar-list-item navbar-button-link" %></li>
    </ul>
  </nav>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_importmap_tags %>

  <!-- Bootstrap Links -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <!-- Personal Styles -->
  <%= stylesheet_link_tag "application", "navbar", "recipes","foods", "data-turbo-track": "reload" %>
</head>

<body>

<header class="d-flex flex-column justify-content-center align-items-center">
  <%= render "layouts/navbar" %>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <div class="fluid-container d-flex flex-column justify-content-center align-items-center">
    <%= yield %>
  </div>

  <!-- Boostrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>